import React from 'react';
import './Disclaimer.css';

const Disclaimer = () => {
  return (
    <div className="disclaimer-view">
      <div className="disclaimer-card">
        <div className="disclaimer-header">
          <span className="material-symbols-outlined icon-warning">warning</span>
          <h2 className="gradient-text">Legal Disclaimer</h2>
        </div>
        
        <div className="disclaimer-body">
          <section className="disclaimer-section">
            <h3>Not Legal Advice</h3>
            <p>
              The information provided by <strong>न्याय Netra (Nyaya Netra)</strong> is generated by Artificial Intelligence. 
              While we strive for accuracy based on documented penal codes and statutes, this platform is for 
              <strong> informational and educational purposes only</strong>.
            </p>
          </section>

          <section className="disclaimer-section">
            <h3>No Attorney-Client Relationship</h3>
            <p>
              Usage of this AI guardian does not constitute an attorney-client relationship. The analysis provided 
              is a cognitive summary and should not be treated as a substitute for professional legal counsel 
              from a licensed advocate or LLB degree holder.
            </p>
          </section>

          <section className="disclaimer-section">
            <h3>Liability and Accuracy</h3>
            <p>
              Law is subject to interpretation and frequent updates. न्याय Netra shall not be held liable for any decisions 
              made based on the AI's output. Users are strongly encouraged to verify the output with official gazettes 
              or legal professionals before taking any formal action.
            </p>
          </section>

          <div className="disclaimer-glow-divider"></div>

          <section className="disclaimer-section highlight-box">
            <p>
              By using this service, you acknowledge that you understand the limitations of AI-driven legal assistance 
              and agree to use it as a guidance tool rather than a final verdict.
            </p>
          </section>
        </div>

        <div className="disclaimer-footer">
          <p className="label">© 2026 Nyaya Netra Technologies • AI Legal Guardian</p>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
